### ISSUE TITLE
Getting sporadic 'Name does not resolve' error

### ISSUE THREAD

**Issue by Constantin07** [andrey-pohilko/registry-cli#72]
While running the below command:
```
docker run --rm anoxis/registry-cli -r <my_registry_url> --delete --num 5
```

I get sporadically the below error:
```
Digest sha256:4e1dd4afa63ce0e0b4584a6531ef1d75acf56af80ecb3cacbcf5c26411058fe7 for tag 4-aa71f04 is referenced by another tag or has already been deleted and will be ignored
Digest sha256:f84d2f1e26e3f5ba116ddc20f2847fced56e47e17ebea122ccd649df517fd0e8 for tag 4-eedce7c is referenced by another tag or has already been deleted and will be ignored
Traceback (most recent call last):
  File "/registry.py", line 804, in <module>
    main_loop(args)
  File "/registry.py", line 793, in main_loop
    tags_list_to_delete, keep_tags)
  File "/registry.py", line 583, in delete_tags
    task.get()
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
requests.exceptions.ConnectionError: HTTPConnectionPool(host='my_registry_url', port=5000): Max retries exceeded with url: /v2/tool-box/manifests/5-78b2630 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1328fba790>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
```

If I re-run it again, the error is gone. 
I definitely have no connectivity issues from the host I'm running the script.

Any ideas what the issue could be ?

**Comment by NorekZ** [comment]
I have the same issue... any suggestions?

**Comment by mikafouenski** [comment]
Hello, this is still happening.

Running the latest docker registry `2.7.1`

```
---------------------------------
Image: redacted
  tag: 20190922
  tag: 20190915
  tag: 2020.9
  tag: 2019.3
---------------------------------
Image: redacted
  tag: 20190708
  tag: 2019.3
---------------------------------
Image: redacted
  tag: 20190908
  tag: 20190915
  tag: 20190922
  tag: 2019.3
---------------------------------
Image: redacted
    main_loop(args)
  File "/registry.py", line 794, in main_loop
    all_tags_list = registry.list_tags(image_name)
  File "/registry.py", line 275, in list_tags
    result = self.send("/v2/{0}/tags/list".format(image_name))
  File "/registry.py", line 253, in send
    verify=not self.no_validate_ssl)
  File "/registry.py", line 60, in request
    return requests.request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='redacted', port=5000): Max retries exceeded with url: /v2/redacted/tags/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe963cc090>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
```

Any clue why the name is resolved at first, we have output, and then it doesn't resolve anymore ?
